name: Atualizar Catalogo

on:
  schedule:
    - cron: '0 12,15,19,23 * * *'  # horários específicos (Brasil ajustado)
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Instalar libs
        run: pip install requests beautifulsoup4

      - name: Rodar importador
        env:
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
        run: python script.py
        continue-on-error: false
