name: Atualizar Catalogo

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *'

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar site
        run: |
          curl -L "https://catalogo.innosystem.com.br/atacadoaj_g2" -o site.html

      - name: Mostrar arquivo
        run: cat site.html
